spring.application.name=br
spring.datasource.url=jdbc:mysql://localhost:3306/lojaWeb
spring.datasource.username=root
spring.datasource.password=G1vt24DiFw1996

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
